---
- name: Configure a appsvcs iapp service using parameters in JSON document
  bigip_iapp_service:
    name: "app2_svcs"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    template: "appsvcs_integration_v2.0.003"
    validate_certs: "false"
    state: "{{ state }}"
    parameters: "{{ lookup('file', 'app2.json') }}"
    parent: "include_defaults.json"
  delegate_to: localhost
...
